### ISSUE TITLE
Doesn't check if ticket is addressless

### ISSUE THREAD

**Issue by LaHaine** [hautreux/auks#1]
I'm testing slurm with auks. In my Kerberos setup, tickets aren't addressless by default. If I submit a slurm job with auks enabled, the job will get a ticket that looks addressless but cannot be used, e.g. I get this error:
# kinit -R

kinit: krb5_get_kdc_cred: Incorrect net address

If I get an addressless ticket with kinit -A before submitting to slurm, the ticket can be renewed with kinit -R just fine.

**Comment by hautreux** [comment]
FYI, the patch has just been merged on heimdal :
https://github.com/heimdal/heimdal/pull/103

HTH
