### ISSUE TITLE
LogFile ignored

### ISSUE THREAD

**Issue by robberteggermont** [hautreux/auks#10]
Since upgrading to the latest version on github (commit aa2eb6b), auksd and auksdrenewer ignore the specified LogFile but instead log to stdout (/var/log/messages).

Logging to the specified LogFile was working at least up to and including commit 31aadac.

**Comment by hautreux** [comment]
As stated in the changelog file, auks now uses systemd 'simple' type and as a consequence, journalctl to manage the logs. As you spawn auks using systemd, log files conf entries are just ignored.

**Comment by robberteggermont** [comment]
Sorry, I missed that (or forgot about it?), and the auks.conf manpage and example didn't offer any clues. I'll add a note to my auks.conf. ;-)
Would it be an idea to add a note to the auks.conf manpage and example?

**Comment by hautreux** [comment]
I 'll add notes in the man pages.

**Comment by hautreux** [comment]
notes added in commit 252c78d
