### ISSUE TITLE
auks with keyring credential cache type rather than file type

### ISSUE THREAD

**Issue by sreedharmanchu** [hautreux/auks#11]
Hi,

How do I get around where if we use keyring credential cache type for kerberos rather than file type? Right now, it doesn't work until I comment out keyring option in our krb5.conf

default_ccache_name = KEYRING:persistent:%{uid}

Then, by default it's putting cache as file type and things work fine.

Do you have any suggestions? Thanks in advance

Best,
Sreedhar.

**Comment by hautreux** [comment]
I do not have enough knowledge of how ccache are managed using keyring to help you on that.

That is something that I will have to study in the future but not yet planned.

If you succeed in making this work please let me know. If can review and integrate patches if necessary (in that case keyring support will have to be optional using a new conf pragma and disabled by default).

**Comment by c-mertes** [comment]
Dear @hautreux,
are there any plans to move to the keyring from file for the cache type? We can reproduce the this error on our side too. It works with file but not with keyring.

Best,
Chriss
