### ISSUE TITLE
Compiling on RHEL/CENTOS 7

### ISSUE THREAD

**Issue by axelnagel** [hautreux/auks#14]
Hi there,

thanks for the package.
I had to use the following options to get it to compile on RHEL 7 and Centos 7 pulling the latest code from the repository.
Maybe that info can be added to the INSTALL notes or left here.

`aclocal && libtoolize --force && autoreconf --install`
`./configure`
`./make`

Cheers
 Axel

**Comment by hautreux** [comment]
You can alternatively do a 'autoreconf -fvi', that is what is done when creating RPMs on Redhat/CentOS systems (see auks.spec).

At some point in the future, I should remove the pregenerated autotools files from git and add an autogen.sh script to do that. That is probably the best way to cope with that.

I will let that ticket open to remind me that.

Thanks
