### ISSUE TITLE
/etc/sysconfig/aukspriv: No such file or directory

### ISSUE THREAD

**Issue by robberteggermont** [hautreux/auks#18]
Commit 94f4efab0ec555bea6dc35c4b5abb14bd10df1a0 makes aukspriv.service fail: when /etc/sysconfig/aukspriv doesn't exist, sourcing fails and aukspriv is not started. /etc/sysconfig/aukspriv didn't need to exist before, and it's not created by the rpm during updating.

Correct me if I'm wrong but that commit seems to be a hack to provide something that systemd doesn't support, and I'm wondering if that is the smart thing to do. Is this something that needs to be in the official tree?

**Comment by arno** [comment]
Hi Robbert,

You're totally right. We found a new systemd way to prevent this hack. A commit will be pushed to revert 94f4efab0ec555bea6dc35c4b5abb14bd10df1a0.

Thanks,
Arnaud

**Comment by robberteggermont** [comment]
Hi Arnaud,

Thanks for looking into this, and great to hear you found a solution!

Best,

Robbert

On 20-06-16 10:50, Arnaud Guignard wrote:
> Hi Robbert,
>
> You're totally right. We found a new systemd way to prevent this hack. A
> commit will be pushed to revert 94f4efa
> <https://github.com/hautreux/auks/commit/94f4efab0ec555bea6dc35c4b5abb14bd10df1a0>.
>
> Thanks,
> Arnaud

-- 
Robbert Eggermont                                  Intelligent Systems
R.Eggermont@tudelft.nl         Electr.Eng., Mathematics & Comp.Science
+31 15 27 83234                         Delft University of Technology
