### ISSUE TITLE
Licensing uncertainties

### ISSUE THREAD

**Issue by imphil** [hautreux/auks#20]
Hi,

I'm currently in the progress of packaging auks for Debian/Ubuntu, and I found some strangeness regarding the licensing of auks.

* The COPYING file says it's CeCILL-C "Version 1.0 dated 2006-09-05."
* The FSF Directory has a v2-version of the license on the same date: https://directory.fsf.org/wiki/License:CeCILLv2 (see also https://www.gnu.org/licenses/license-list.en.html#CeCILL)

What was intended here?

(Changing or dual-licensing to GPL or any other well-established license would make things *significantly* easier. I know, of course, that there are sometimes good reasons or requirements to choose a specific license.)

**Comment by imphil** [comment]
Ah, I got confused by the different versions. auks is CeCILL**-C** v1.0 (released on the same day as CeCILL without C v2.0). Since this license is not listed by the FSF and discussions in debian-legal were inconclusive (https://lists.debian.org/debian-legal/2008/01/msg00171.html), this will involve quite some work to get included :-(

**Comment by hautreux** [comment]
In my understanding, CeCill-C was compatible LGPL (
https://en.wikipedia.org/wiki/CeCILL). What is the exact issue regarding
the integration ?

2016-07-19 22:12 GMT+02:00 Philipp Wagner <notifications@github.com>:

**Comment by imphil** [comment]
Debian requires a license review for licenses "unknown" to Debian (other distributions have similar procedures). I didn't find any other CeCILL-C licensed software package in Debian, making auks the first one. (In fact, not much software uses this license, it seems: http://www.cecill.info/logiciels.en.html) 
More details on the debian processes can be found here: https://www.debian.org/legal/licenses/ and https://wiki.debian.org/DFSGLicenses#If_the_license_isn.27t_on_this_list

While the current license is most likely not a showstopper for integration into Debian/Ubuntu, it will take come time and quite some effort to be sorted out. So if it would be possible on your side to relicense or dual-license auks, things would be much easier (just upload and be done, instead of a lengthy discussion with uncertain outcome about legal details).

**Comment by hautreux** [comment]
Ok, I will see what I can do for that, but I am not sure that it will take
less time :(

2016-07-19 23:12 GMT+02:00 Philipp Wagner <notifications@github.com>:

**Comment by hautreux** [comment]
I think that I will move to an LGPL license if all the contributors agree. Do you think that it will be okay with such a license ?

**Comment by imphil** [comment]
Yes, LGPL will make it much easier to get auks into the distributions. Thanks for considering it!

**Comment by hautreux** [comment]
After talking with my colleagues, it appears that one of their product is included in debian/ubuntu using a Cecill-C license so it will not be an issue :
https://packages.debian.org/en/sid/clustershell (see Copyright file)

Please reopen if necessary.
