### ISSUE TITLE
renewer: unable to dump auksd creds : auks api : request processing failed

### ISSUE THREAD

**Issue by swallace21** [hautreux/auks#26]
auksdrenewer.c - line 181
```
/* dump auks creds table */
fstatus = auks_api_dump(engine,&creds,&creds_nb);
```
auks_api_dump <- line 445 auks_api.c

Any ideas as to what the issue might be? Thanks!

**Comment by hautreux** [comment]
You need to ensure that the principal of the host running auksdrenewer has
the admin privilege in auks.acl. do not forget to reload auksd when you
modify this file for changes to be taken into account.


Le 13 août 2018 10:01 PM, "Shaun Wallace" <notifications@github.com> a
écrit :

auksdrenewer.c - line 181

/* dump auks creds table */
fstatus = auks_api_dump(engine,&creds,&creds_nb);

auks_api_dump <- line 445 auks_api.c

Any ideas as to what the issue might be? Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hautreux/auks/issues/26>, or mute the thread

**Comment by swallace21** [comment]
Thanks for the quick response. :) Still getting the same error. Here are parts of the config:

auks.conf
```
 # Primary daemon configuration
 PrimaryHost        = 	"phostname" ;
 PrimaryPort        = 	12345 ;
 PrimaryPrincipal   = 	"host/phostname.com@KDC.COM" ;
```

auksd.acl
```
rule {
         principal = host/phostname.com/KDC.COM;
	 host = * ;
         role = admin;
}
```

**Comment by hautreux** [comment]
Is host/phostname.com/KDC.COM in auksd.acl a typo in your message ? It
should be  host/phostname.com@KDC.COM


Le mar. 14 août 2018 à 14:56, Shaun Wallace <notifications@github.com> a
écrit :

**Comment by swallace21** [comment]
Yup that was a typo. It is now partially working.

**Current Status:**
Got auks api to run commands w/out errors. But, auksdrenewer is still reporting the same error.

aukspriv - no errors in logs
auksd - no errors in logs
auksdrenewer - running w/ error
```
Aug 14 10:18:44 vm.name auksdrenewer[4352]: Tue Aug 14 10:18:44 2018 [INFO1] [euid=0,pid=4352] renewer: unable to dump auksd creds : auks api : request processing failed
Aug 14 10:18:44 vm.name auksdrenewer[4352]: Tue Aug 14 10:18:44 2018 [INFO1] [euid=0,pid=4352] renewer: 32659 creds renewed in ~0s
```


**Observations:**

To run the auks api as a user you need a pre-existing kerberos ticket. If you run kdestroy, then 

When exiting a VM your AUKS kerberos ticket is destroyed.

```
AUKS api is not reading credential cache correctly:
[uid@vm.name ~]$ auks -R once
Auks API request failed : auks cred : credential is still valid
[uid@vm.name ~]$ klist
Ticket cache: FILE:/tmp/krb5cc_763456255
Default principal: uid@KDC.COM

Valid starting       Expires              Service principal
08/14/2018 10:25:51  08/14/2018 20:25:51  krbtgt/KDC.COM@KDC.COM
	renew until 08/15/2018 10:25:49
```

**Comment by swallace21** [comment]
Another interesting behavior. If you have a kerberos ticket created by running:
auks -p
Then running kinit will destroy it.

Are these observed behaviors intentional? Thanks!

**Comment by hautreux** [comment]
'auks -p' is a ping command that checks that the auks server is reachable by the client and that both sides can perform a mutual kerberos authentication properly.

Thus a TGS is fetched in the krb5 credential cache automatically by the underlying kerberos library and visible with klist after the operation

**Comment by hautreux** [comment]
If you kdestroy/kinit, then the krb5 credential cache is reinitialized and the fetched TGS is lost. It will be fetched again at the next access to the auks server.

**Comment by hautreux** [comment]
You need to check that your auksdrenewer process has a valid credential cache that corresponds to a principal associated to the admin privilege in auksd.acl. can you confirm that you have properly checked that ?

**Comment by hautreux** [comment]
'auks -R once' is not the best command to check that everything is working fine from the client side.
As a user, you should try 'auks -a' that adds a TGT for the client on the server and 'auks -g' that get a TGT from the server and store it in the current (or targeted) credential cache.
As a user/principal with admin privilege, you should try 'auks -g -u %target-uid% -c ....' .

**Comment by hautreux** [comment]
Did you make things work ? Can I close this one ?

**Comment by swallace21** [comment]
Sorry for the late reply. Could not get it to work, had to shelve the project for other more pressing matters. Will be re-attempting soon.
