### ISSUE TITLE
High availability configuration for auks?

### ISSUE THREAD

**Issue by robberteggermont** [hautreux/auks#36]
Auks comes with some support for high availability (using a secondary auksd). The auksd man page does not mention a secondary auksd at all, but the auks.conf man page does mention this:

> Current version of auksd assumes that when the secondary daemon is started, the primary is stopped. Secondary  daemon  starts  processing  requests  as  soon  as  it starts. External Fail-Over mechanism must be used to ensure that only one daemon is active at a time.

However, I have not been able to find a recipe for an external fail-over mechanism for auksd. Does one exist? (This [talk](http://workshop.openafs.org/afsbpw10/talks/wed_3/hautreux_kerberos_hpc.pdf) mentions PaceMaker, but nothing on configuration.)

The reason that only one auksd can be active is that there is no mechanism to synchronize added, renewed or removed credentials between multiple auksd. /var/cache/auks is only read once at the start, after that auksd works from an in-memory copy of the credentials. Any changes (additions, renewals, removals) are written back to /var/cache/auks, but auksd does not have a mechanism to detect changes to /var/cache/auks. (A crude workaround would be to manually add the credentials from /var/cache/auks to the secondary auksd every couple of minutes.)

But what about high availibility for  the auksdrenewer? The auksdrenewer man page states:

> Only one auksdrenewer should be active at a time. This daemon automatically switch to the backup auksd daemon in case  of  problems with the first one.

So in case auksdrenewer fails, you again need an external fail-over mechanism to a secondary auksdrenewer.

Did anyone set up auks with a fail over to a secondary auksd (and auksdrenewer), and if so, how?

Are there any plans to add built-in support for automatic fail-over, or for supporting an active/active configuration with automatic synchronization?

**Comment by hautreux** [comment]
While we are still heavily using auks on our systems, we do not plan to add any new features for now.

The secondary auksd daemon is pretty useless in common scenarii and you should just focus on having one auksd daemon, an associated renewer and a credential cache directory on a FS that can be activated on a second node (that would take over using pacemaker or something similar) if the first one fails.

**Comment by robberteggermont** [comment]
Seeing the complexity of a pacemaker solution makes me really really want to want to hack together a nice and simple 'auks -p || systemctl start auksd' solution. ;-)
Or maybe run active/active and monitor the logs and for every credential added do another 'auks -a' to the other auksd.

So suggestions for a pacemaker configuration or the above "hacks" are very welcome. (I don't want to failover the whole server, just auksd, since I have other services running on these nodes as well.)

Any suggestions on what timeout to use for the failover? (I think by default auks does 3 tries with a 10 second timeout and 10 second delay, so the secondary auksd should be online within about 30 seconds after the primary fails?)

**Comment by hautreux** [comment]
Yes, less than 30s to make the backup service start with the 3*10s timeouts seems necessary.
Closing this as you have probably managed that in the meantime :)
