### ISSUE TITLE
compile on EL8

### ISSUE THREAD

**Issue by jbrnfnd** [hautreux/auks#37]
Hello, I am trying to compile auks on CentOS8.
At first, I need to do "autoreconf -i" for installing "ar-lib" and "ylwrap"

configure works
while doing make, the following error appears
xmessage.c:82:10: fatal error: rpc/types.h: No such file or directory
 #include <rpc/types.h>
          ^~~~~~~~~~~~~

/usr/include/rpc/types.h came from the glibc-devel package in EL7
Now its included in libtirpc-devel and the path changed to /usr/include/tirpc/rpc/types.h

I am not really aware with changing configure or makefile to get it work. I have tried setting CFLAGS to "-I/usr/include/tirpc" in the Makefile, but this did not help.

Can anyone help me?
Thanks in Advance
Jens

**Comment by LaHaine** [comment]
The workaround would be to use `make CPPFLAGS=-I/usr/include/tirpc LIBS=-ltirpc`, the fix would be a configure check for the header and the library.

**Comment by hautreux** [comment]
A fix is now included.

**Comment by LaHaine** [comment]
The fix doesn't work:
```
Making all in xternal
make[4]: Entering directory '/tmp/waschk/auks/src/api/xternal'
Makefile:193: *** Recursive variable 'AM_CPPFLAGS' references itself (eventually).  Stop.


```

**Comment by hautreux** [comment]
You are right, I pushed the wrong branch. I have just forced push the right one, sorry for the inconvenience (and for the forced push...).
