### ISSUE TITLE
Auks API init failed : unable to parse configuration file

### ISSUE THREAD

**Issue by robberteggermont** [hautreux/auks#4]
After applying the latest auks commit (31aadac9ed) from github, auks and auksd ignore /etc/auks/auks.conf and instead return 'unable to parse configuration file'.

It seems both auks and auksd are looking for /etc/auks.conf instead (creating a symlink from /etc/auks.conf to /etc/auks/auks.conf makes both work).

**Comment by robberteggermont** [comment]
This seems to have been corrected in commit b6f311b.

**Comment by hautreux** [comment]
Yes, thanks for closing it.
