### ISSUE TITLE
auksdrenewer needed on compute nodes?

### ISSUE THREAD

**Issue by DriesVerachtert** [hautreux/auks#40]
Hello,
We have slurm with auks working, but one thing is not 100% clear to me from reading the documentation: does auksdrenewer just renew the tickets stored in auksd, so 1 or 2 auksdrenewer processes on for example the login nodes is good enough? Or are they for some reason also needed on each compute node?
Kind regards and thank you in advance for any information.
Dries

**Comment by hautreux** [comment]
Hello,

One auksdrenewer is sufficient, it can be colocated with auksd on a same node for example. Auks slurm spank plugin will regularly get renewed credential from auksd during job execution. This logic reduces the load on the kdc server for renewing user credentials.
