### ISSUE TITLE
mit-krb5 >=1.18

### ISSUE THREAD

**Issue by kenshin33** [hautreux/auks#46]
FYI 
https://github.com/krb5/krb5/commit/dcb853ac32779b173f39e19c0f24b0087de85771
renamed krb5_rc_close (-> k5_rc_close)  and krb5_rc_resolve_full ( -> k5_rc_resolve)

**Comment by hautreux** [comment]
fixed in version 0.5.3 by b84ae7334400bf1c5dd458bdc530b2939bbd4cdc
