### ISSUE TITLE
Fixing a few typos in the HOWTO

### ISSUE THREAD

**Issue by whamblen** [hautreux/auks#54]
It's mostly stuff like

host/mngt.realm.a/REALM.A -> host/mngt.realm.a@REALM.A

patch file attached
[HOWTO.txt](https://github.com/hautreux/auks/files/6102717/HOWTO.txt)

I didn't put this in the patch but line 406 says to run "auks -a" as root.  In general this won't work.  See issue #27 .  Maybe just delete that piece of the component test?

**Comment by hautreux** [comment]
fixed in 894fad208542b9a32dd88cf303caf9bd82e7ca99, thanks
