### ISSUE TITLE
systemd not starting aukspriv on compute node

### ISSUE THREAD

**Issue by robberteggermont** [hautreux/auks#7]
The aukspriv.service file defines `WantedBy=auksdrenewer.service`.
However, on compute nodes auksdrenewer is not enabled, so systemd leaves aukspriv inactive.

Changing the line to `WantedBy=auksdrenewer.service slurmd.service` makes systemd start aukspriv for slurmd, as would a `Wants=aukspriv.service` line in slurmd.service. But maybe a more general solution like `WantedBy=multi-user.target` may be more appropriate?

**Comment by hautreux** [comment]
I am not sure that putting a dependency on slurmd.service inside auks systemd configuration is interesting. auks must be considered as a standalone app that can be used to add kerberos support to Slurm if necessary. I'd rather only have references to auks related components inside auks systemd scripts.
On compute node, you just have to enable aukspriv and then all should go well, no ? (We do that using puppet).

**Comment by robberteggermont** [comment]
No, it's not being started automatically by systemd on boot (on CentOS 7.2), so for a general solution I guess a WantedBy=multi-user.target is needed.

# systemctl status aukspriv
● aukspriv.service - Auks ccache from keytab scripted daemon
   Loaded: loaded (/usr/lib/systemd/system/aukspriv.service; enabled; vendor preset: disabled)
   Active: inactive (dead)

**Comment by hautreux** [comment]
Can you provide the log output of the aukspriv service to see what is the reason of the termination ? Which version are you using ? Have you tried the multi-user.target and does it corrects the issue or is it a proposal that you have not yet try ?

**Comment by robberteggermont** [comment]
There is no logging whatsoever (journalctl doesn't produce any output and there's nothing in /var/log/messages), indicating to me it's simply not being started.

If it would be terminating, the output from systemctl status would indicate that:
```bash
# killall aukspriv
# systemctl status aukspriv
● aukspriv.service - Auks ccache from keytab scripted daemon
   Loaded: loaded (/usr/lib/systemd/system/aukspriv.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since vr 2016-01-22 10:47:20 CET; 2s ago
  Process: 878 ExecStart=/usr/sbin/aukspriv $AUKSPRIV_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 892 (code=killed, signal=TERM)

jan 22 10:21:27 insytest70 systemd[1]: Starting Auks ccache from keytab scripted daemon...
jan 22 10:21:27 insytest70 systemd[1]: Started Auks ccache from keytab scripted daemon.
```

I'm building directly from git (0.4.4.1447847456.aa2eb6b at the moment).

I have tested the multi-user.target and it seems to work for me so far.

**Comment by hautreux** [comment]
Ok, please do a PR and I will merge it.

Le ven. 22 janv. 2016 10:54, robberteggermont <notifications@github.com> a
écrit :

**Comment by robberteggermont** [comment]
On 22-01-16 17:43, hautreux wrote:
> Ok, please do a PR and I will merge it.

Done. I simply replaced auksdrenewer.service by the generic 
multi-user.target.

Best,

Robbert

-- 
Robbert Eggermont                                  Intelligent Systems
R.Eggermont@tudelft.nl         Electr.Eng., Mathematics & Comp.Science
+31 15 27 83234                         Delft University of Technology
